<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
	<title>CinemALL</title>
    <meta name="description" content="Page utilisateur CinemALL">
	<?php require "includes/partials/page_head.phtml"; ?>
	<link href='https://fonts.googleapis.com/css?family=Russo One' rel='stylesheet'>
	<link rel="stylesheet" href="public/styles/styles.css" type="text/css" />
</head>
<body>
	<nav>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</nav>
	<header>
		<h1>Page Utilisateur</h1>
	</header>
	<main class="">
		<section class="userContainer">
            <img src="<?= $maPersonne->getAvatar() ?>" class="avatar"></img>
    	</section>
    	<?php 
    		print("<a href=\"index.php?page=contact&action=edit&id={$maPersonne->getId()}\" class='editUser'>Modifier mon profil</a>");
    		
			if (isset($_SESSION['login']) && $_SESSION['login'] != '' && $_SESSION['isAdmin'] == 1){
				
        		print('<h4 class="titleAdmin">Mode ADMIN</h4>');
				print('<script>let idPersonne='.$_SESSION['idUser'].';</script>');
			?>	
				<div class="addVisu">
					<a href="index.php?page=contact&action=add">Ajouter un contact</a>
				</div>
				<table class="tableVisu">
					<h2>Liste Utilisateur</h2>
					<thead>
						<th>Email</th>
						<!--<th>Password</th>-->
						<th>Avatar</th>
						<th>Date Naissance</th>
						<th colspan="2">Actions</th>
					</thead>
					<tbody class="">
						<?php
							foreach ($lesContacts as $unContact){
								print('<tr>');
								print('<td class="tbVisu">'.$unContact->getEmail().'</td>');
								//print('<td>'.$unContact->getPassword().'</td>');
								print('<td class="tbVisu">'.$unContact->getAvatar().'</td>');
								print('<td class="tbVisu">'.$unContact->getDateNaissance()->format('d/m/Y').'</td>');
								print("<td class='tbVisu'><a href=\"index.php?page=contact&action=edit&id={$unContact->getId()}\">Modifier</a></td>");
								print('<td class="tbVisu"><a href="index.php?page=contact&action=delete&id='.$unContact->getId().'">Supprimer</a></td>');
								print('</tr>');
							}
						?>
					</tbody>
				</table>
				<table class="tableNewsletter">
					<h2>Newsletter</h2>
					<thead>
						<th>Email</th>
						<!--<th>Password</th>-->
						<th>Date ajout</th>
						<th colspan="2">Actions</th>
					</thead>
					<tbody class="">
						<?php
							forEach ($lesNewsletters as $uneNewsletter){
								print('<tr>');
								print('<td class="tbVisu">'.$uneNewsletter->getEmail().'</td>');
								print('<td class="tbVisu">'.$uneNewsletter->getDateEnvoi().'</td>');
								//print("<td class='tbVisu'><a href=\"index.php?page=contact&action=edit&id={$unContact->getId()}\">Modifier</a></td>");
								print('<td class="tbVisu"><a href="index.php?page=newsletter&action=delete&id='.$uneNewsletter->getId().'">Supprimer</a></td>');
								print('</tr>');
							}
						?>
					</tbody>
				</table>
				<?php
			}else{
				print('<script>if(typeof idPersonne === \'undefined\') {let idPersonne = 0;}</script>');
				?>
				<div class="userListMovie">
				<div class="userMovieFavorite">
					<h2>Vos Films favoris</h2>
						<div class="userFavorite">
					</div>
				</div>
				<div class="userMovieSee">
					<h2>Vos films déjà vu</h2>
					<div class="userSee">
						
					</div>
				</div>
				<div class="userMovieFutur">
					<h2>Films à voir</h2>
					<div class="userFutur">
					
					</div>
				</div>
			</div>
			<?php
			}
			?>
	</main>
	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
</body>
<script type="text/javascript" src="public/scripts/script.js"></script>
<script type="text/javascript" src="public/scripts/script_user_view.js"></script>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
	    const idFilms =  <?php echo json_encode($idFilms); ?>;
	    const idFilms2 = <?php echo json_encode($idFilms2); ?>;
	    const idFilms3 = <?php echo json_encode($idFilms3); ?>;
	    idFilms.forEach(async function(idFilm) {
	      let userInfoPage = await getUserInfo(idFilm);
	      createUserContent(userInfoPage, '.userFavorite');
	    });
	    idFilms2.forEach(async function(idFilm2) {
	      let userInfoPage2 = await getUserInfo(idFilm2);
	      createUserContent(userInfoPage2, '.userSee');
	    });
	    idFilms3.forEach(async function(idFilm3) {
	      let userInfoPage3 = await getUserInfo(idFilm3);
	      createUserContent(userInfoPage3, '.userFutur');
	    });
	});	  
</script> 
</html>